import fs from 'fs';

let text = fs.readFileSync('src/components/AdminPanel.tsx', 'utf8');

const translations: Record<string, string> = {
  'Sâmbătă Seara': 'Saturday Evening',
  'Slujba de seară de sâmbătă prin care se intră în ziua Domnului, deschizând programul duminical.': 'The Saturday evening service entering the Lord\'s day, opening the Sunday program.',
  'Utrenia (Slujba de Dimineață)': 'Matins (Morning Service)',
  'În fiecare Duminică': 'Every Sunday',
  'Pregătirea duhovnicească a inimilor prin laude de dimineață înaintea Sfintei Liturghii.': 'Spiritual preparation of hearts through morning praises before the Holy Liturgy.',
  'Sfânta Jertfă Euharistică, inima comunității noastre. Săvârșită în limba engleză.': 'The Holy Eucharistic Sacrifice, the heart of our community. Served in English.',
  'Agapa Frățească (Gustare / Socializare)': 'Fellowship Agape (Snack / Socializing)',
  'Fiecare este binevenit să aducă alimente pentru a fi binecuvântate și împărtășite împreună la agapă.': 'Everyone is welcome to bring food to be blessed and shared together at the agape.',
  'Slujbele noastre de duminică încep cu Utrenia la ora 09:00 și Sfânta Liturghie la 10:00.': 'Our Sunday services begin with Matins at 09:00 and Holy Liturgy at 10:00.',
  'Slujbă nouă': 'New Service',
  'Sâmbătă': 'Saturday',
  'Sigur doriți să ștergeți această slujbă?': 'Are you sure you want to delete this service?',
  'S-a atins limita maximă de 500 de fotografii parohiale. Deleteți-le pe cele vechi.': 'The maximum limit of 500 parish photos has been reached. Please delete old ones.',
  'Auto-save direct în Firestore pentru a apărea imediat pe site:': 'Auto-save direct to Firestore to appear immediately on site:',
  'Fotografia a fost încărcată cu succes și este vizibilă pe site!': 'Photo successfully uploaded and is visible on the site!',
  'Logoul a fost încărcat și salvat online cu succes!': 'Logo successfully uploaded and saved online!',
  'Fotografia principală a fost încărcată și salvată online cu succes!': 'Main photo successfully uploaded and saved online!',
  'Fotografia principală a fost salvată online cu succes!': 'Main photo successfully saved online!',
  'Te rog adaugă un link URL valid.': 'Please add a valid URL link.',
  'Limita maximă este de 500 de fotografii parohiale.': 'Maximum limit is 500 parish photos.',
  'Fotografia a fost adăugată și salvată online cu succes!': 'Photo successfully added and saved online!',
  'Fotografia a fost ștearsă din listă.': 'Photo deleted from list.',
  'Vă rugăm să introduceți link-ul video-ului de YouTube.': 'Please enter the YouTube video link.',
  'Adresa video-ului nu pare să fie corectă. Fiți sigur că este un link valid spre YouTube (ex: https://www.youtube.com/watch?v=... sau https://youtu.be/...).': 'Video address seems incorrect. Ensure it is a valid YouTube link (e.g. https://www.youtube.com/watch?v=... or https://youtu.be/...).',
  'Video adăugat și salvat cu succes!': 'Video added and saved successfully!',
  'Modificările au fost salvate pe serverul Firestore!': 'Changes saved to Firestore server!',
  'Se încarcă datele din baza de date Firestore...': 'Loading data from Firestore database...',
  'Previzualizare în timp real (Sinergie directă cu Pagina Publică)': 'Real-time Preview (Direct Synergy with Public Page)',
  'Ascunde previzualizarea': 'Hide preview',
  'Afișează previzualizarea': 'Show preview',
  '* Această secțiune simulează felul în care vor arăta anunțul și slujbele pe pagina principală a site-ului cu modificările curente (chiar și cele nesalvate).': '* This section simulates how the announcement and services will look on the site main page with current changes (even unsaved ones).',
  '2. Simulare Carduri Slujbe (Sinergie 1-la-1 cu Pagina Principală):': '2. Service Cards Simulation (1-to-1 Synergy with Main Page):',
  'Română / RO': 'Romanian / RO',
  'Toate slujbele sunt ascunse sau nu există date.': 'All services are hidden or no data exists.',
  'Afișat în partea de sus a sălii de calendar pentru enoriași': 'Displayed at the top of the calendar section for parishioners',
  'Activează Anunțul în Site': 'Enable Announcement on Site',
  'Bifează pentru ca anunțul să apară pe ecran, debifează pentru a-l ascunde.': 'Check for announcement to appear on screen, uncheck to hide it.',
  'Conținutul anunțului în română...': 'Announcement content in Romanian...',
  'Dacă nu aveți nevoie de Vecernia de sâmbătă': 'If you do not need Saturday Vespers',
  ', puteți pur și simplu să o ștergeți sau să o dezactivați prin butonul de ștergere (🗑️) de pe slujba respectivă. Pentru a o reactiva, folosiți butonul „Adaugă slujbă” și asigurați-vă că tipul este setat pe „Vecernie”.': ', you can simply delete or disable it via the delete button (🗑️) on that service. To reactivate it, use the "Add Service" button and make sure the type is set to "Vespers".',
  'Mută mai Sus': 'Move Up',
  'Mută mai Jos': 'Move Down',
  'Slot 1 pe Prima Pagină (Vecernie Sâmbătă)': 'Slot 1 on Main Page (Saturday Vespers)',
  'Slot 2 pe Prima Pagină (Utrenie Duminică)': 'Slot 2 on Main Page (Sunday Matins)',
  'Slot 3 pe Prima Pagină (Sfânta Liturghie)': 'Slot 3 on Main Page (Holy Liturgy)',
  'Slot 4 pe Prima Pagină (Agapă / Tratații)': 'Slot 4 on Main Page (Agape / Refreshments)',
  'Încarcă Model (Preset):': 'Load Preset:',
  'Agapă / Gustare (Refreshments for All)': 'Agape / Snack (Refreshments for All)',
  'Sigur doriți să GOLIȚI complet toate datele acestui slot? Aceasta va șterge textul, dar va păstra slotul în listă pentru a-l edita manual.': 'Are you sure you want to completely CLEAR all data from this slot? This will delete the text but keep the slot in the list for manual editing.',
  'Ex: 09:00 sau duminică': 'Ex: 09:00 or Sunday',
  'Ex: În fiecare Duminică': 'Ex: Every Sunday',
  'Numele în română...': 'Name in Romanian...',
  'Detalii liturgice în română...': 'Liturgical details in Romanian...',
  'Sfânta Taină (Roșu / Crimson)': 'Holy Sacrament (Red / Crimson)',
  'Agapă / Slujbe specifice (Verde / Emerald)': 'Agape / Specific Services (Green / Emerald)',
  'Imagine principală la începutul paginii (Preot și Mitropolit)': 'Main image at top of page (Priest and Metropolitan)',
  'Fotografie Principală Hero': 'Hero Main Photo',
  'Încarcă Imagine (Fișier)': 'Upload Image (File)',
  'Încărcați fotografii reprezentative și adăugați link-uri video YouTube pentru enoriași': 'Upload representative photos and add YouTube video links for parishioners',
  'Încărcare Fotografii': 'Photo Upload',
  'Selectați sau trageți fișiere de tip imagine. Sistemul le va redimensiona automat la dimensiuni optime (max 1000px) pentru a reduce încărcarea site-ului.': 'Select or drag image files. The system will automatically resize them to optimal dimensions (max 1000px) to reduce site load.',
  'Descriere / Legendă Foto (opțional)': 'Photo Description / Caption (optional)',
  'Se încarcă...': 'Loading...',
  'Dă drumul imaginii!': 'Drop image!',
  'Alege sau trage fișierul': 'Choose or drag file',
  'Adaugă Link Foto': 'Add Photo Link',
  'Nicio fotografie adăugată încă.': 'No photos added yet.',
  'Adăugare Material Video YouTube': 'Add YouTube Video Material',
  'Adaugă Legătură Video': 'Add Video Link',
  'Niciun material video adăugat încă.': 'No video material added yet.'
};

for (const [ro, en] of Object.entries(translations)) {
  text = text.split(ro).join(en);
}

fs.writeFileSync('src/components/AdminPanel.tsx', text);
